[package]
name = "sc-mapper"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
thiserror = "2"
shell-words = "1"

rust-htslib.workspace = true
hts-sys =  { git = "https://github.com/stela2502/hts-sys.git" }


bam_tide = { path = "../bam_tide" }
anyhow = "1.0.103"
nix = { version = "0.31", features = ["fs"] } 
tempfile = "3.27.0"

