[package]
name = "scdata"
version = "0.2.3"
edition = "2024"

description = "High-performance Rust library for constructing sparse single-cell UMI count data with deterministic MatrixMarket export"

license = "MIT"

documentation = "https://docs.rs/scdata"
repository = "https://github.com/stela2502/scdata"
homepage = "https://github.com/stela2502/scdata"
readme = "README.md"

keywords = ["single-cell", "bioinformatics", "umi", "sparse", "rna-seq"]
categories = ["science", "data-structures"]

[dependencies]
anyhow = "1"
flate2 = "1.1.2"
rayon = "1.10.0"
regex = "1.11.1"

mapping_info = { path = "../mapping_info" }
int-to-str = { path = "../int_to_str" }

[features]
default = []
compare = []
