[workspace]
resolver = "3"
members = [
    "crates/bam_tide",
    "crates/sc-beacon",
    "crates/sc_primer",
    "crates/sc-mapper",
    "crates/gtf_splice_index",
    "crates/fast_tag_mapper",
    "crates/snp-index",
    "crates/scdata",
    "crates/mapping_info",
    "crates/lumrik-status",
    "crates/read-tag-table",
    "crates/int_to_str", 
    "crates/nelrune", 
    "crates/sc-vdj",
    "crates/sc-te",
    "crates/data_table",
]

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
authors = ["Stefan Lang"]


[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
rust-htslib = { path = "crates/rust-htslib" }
