use clap::Parser;
use std::path::PathBuf;
use sc_primer::PrimerCli;
use read_tag_table::ReadTagTableCli;

#[derive(Debug, Clone, Parser)]
#[command(
    author,
    version,
    about = "Restore single-cell primer sequence to normalized FASTQ reads",
    long_about = "\
Restore primer-derived cell/UMI sequence to normalized FASTQ reads.

The tool reads normalized insert FASTQ records and a read tag table generated by
the normalizer. For each FASTQ record it looks up the read id, reconstructs the
single-cell primer sequence from the stored cell/UMI/sample information, prepends
that primer to the insert, and writes a restored FASTQ record.

Reads without matching tag information are not emitted.

By default, any missing tag or restore error causes a non-zero exit code.

Typical use:

    primer-restore \\
      --fastq normalized.fastq.gz \\
      --read-tags read_tags.tsv.gz \\
      --out restored.fastq.gz \\
      --chemistry bd-v2-384
"
)]
pub struct Cli {
    #[arg(
        long,
        short = 'i',
        value_name = "FASTQ[.GZ]",
        help = "Input normalized insert FASTQ. Only R1/read sequence is needed."
    )]
    pub fastq: PathBuf,

    #[arg(
        long,
        short,
        value_name = "FASTQ[.GZ]",
        help = "Output restored FASTQ with reconstructed primer prepended."
    )]
    pub out: PathBuf,

    #[command(flatten)]
    pub read_tags: ReadTagTableCli,

    #[command(flatten)]
    pub primer: PrimerCli,

    #[arg(
        long,
        default_value_t = true,
        help = "Exit with an error if any read could not be restored."
    )]
    pub die_on_error: bool,

    #[arg(
        long,
        default_value_t = 1,
        value_name = "0-9",
        help = "Gzip compression level for FASTQ output."
    )]
    pub gzip_level: u32,

    #[arg(
        long,
        default_value_t = false,
        help = "Write plain FASTQ instead of gzip-compressed FASTQ."
    )]
    pub no_gzip: bool,
}

impl Cli {
    pub fn parse_args() -> Self {
        Self::parse()
    }
}
