[package]
name = "sc-vdj"
version.workspace = true
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Clean single-cell V(D)J reconstruction for Lumrik/Nelrune"

[dependencies]
anyhow = "1"
clap = { workspace = true }
flate2 = "1"
gtf_splice_index = { path = "../gtf_splice_index" }
rust-htslib = { path = "../rust-htslib" }
scdata = { path = "../scdata" }
int-to-str = { path = "../int_to_str" }

[dev-dependencies]
tempfile = "3"
