[package]
name = "fast_tag_mapper"
version.workspace = true
edition = "2021"
description = "Fast BD/FASTA feature-id mapper for bam_tide"

[dependencies]
anyhow = "1.0.102"
clap = { workspace = true }
flate2 = "1"

mapping_info = { path = "../mapping_info" }
scdata = { path = "../scdata" }
int-to-dna = { path = "../int_to_dna" }
onehot_dna = { path = "../onehot_dna" }
