[package]
name = "fast_tag_mapper"
version = "0.1.0"
edition = "2021"
description = "Fast BD/FASTA feature-id mapper for bam_tide"

[dependencies]
anyhow = "1.0.102"
clap = { workspace = true }

mapping_info = { path = "../mapping_info" }
scdata = { path = "../scdata" }
int-to-str = { path = "../int_to_str" }

