[package]
name = "clonomap"
version = "0.4.2"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "Mutation-aware PCA and MST analysis of large receptor clones for Lumrik"


[dependencies]
reference_curator = { path = "../reference_curator" }
ndarray = "0.15"
linfa = "0.7"
linfa-reduction = "0.7"
plotters = {
    version = "0.3",
    default-features = false,
    features = ["svg_backend", "line_series", "point_series"]
}
rayon = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
statrs = "0.18"
sc_primer = { path = "../sc_primer" }
