[package]
name = "sc-beacon"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "Identifies genuine cellular feature signals relative to experimentally measured ambient background"
repository = "https://github.com/stela2502/lumrik"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
statrs = "0.18"
rayon = "1.12.0"

mapping_info = { path = "../mapping_info" }
scdata = { path = "../scdata" }
int-to-str = { path = "../int_to_str" }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "lumrik-guides"
path = "src/main.rs"
