[package]
name = "int-to-dna"
version.workspace = true
edition = "2021"

description = "Fast compact DNA sequence/integer conversion utilities optimized for high-throughput bioinformatics."
license = "MIT"
repository = "https://github.com/stela2502/int_to_dna"
homepage = "https://github.com/stela2502/int_to_dna"
documentation = "https://docs.rs/int-to-dna"
readme = "README.md"

keywords = ["integer", "conversion", "performance", "bioinformatics"]
categories = ["algorithms"]

authors = ["Stefan Lang"]

[dependencies]
clap = { workspace = true }
onehot_dna = { path = "../onehot_dna" }
int-to-prot = { path = "../int_to_prot" }


[features]
default = []
alignment = []
