[package]
name = "nelrune"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nelrune"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rayon = "1"

bam_tide = { path = "../bam_tide" }
gtf_splice_index = { path = "../gtf_splice_index" }
mapping_info = { path = "../mapping_info" }
sc-mapper = { path = "../sc-mapper" }
sc_primer = { path = "../sc_primer" }
scdata = { path="../scdata" }
rust-htslib = { workspace = true }

[dev-dependencies]
flate2 = "1"
scdata = { path = "../scdata" }
snp-index = { path = "../snp-index" }
